version: '2.1'

volumes:
  geoserver-data:
  geo-db-data:

services:
  db:
    image: kartoza/postgis:11.0-2.5
    volumes:
      - geo-db-data:/var/lib/postgresql
    ports:
      - "25434:5432"
    env_file:
      - db.env
    restart: on-failure
    healthcheck:
      test: "exit 0"

  geoserver:
    image: ledsys/geoserver:1
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
    ports:
      - "8600:8080"
    restart: on-failure
    env_file:
      - geoserver.env
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

  neo4j:
    image: neo4j:3.5.3
    ports:
      - "17474:7474"